# Generated by Django 3.2.4 on 2021-07-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_reject_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoredRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('request.request',),
        ),
        migrations.AlterField(
            model_name='request',
            name='reject_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
